// lib/firebase_options.dart
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfSgs-3R5rNSZctxWoQvy9nTaAa_gyXCs',
    appId: '1:1026154962883:web:9cd6ddf026bd0be930e776',
    messagingSenderId: '1026154962883',
    projectId: 'bank-bocil-ec07c',
    authDomain: 'bank-bocil-ec07c.firebaseapp.com',
    storageBucket: 'bank-bocil-ec07c.firebasestorage.app',
    measurementId: 'G-WC4JH5H7P4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6_-BKcDMbqbJ_ma7bdRGi3K88MpzOgE8',
    appId: '1:1026154962883:android:894fb67fc4162acc30e776',
    messagingSenderId: '1026154962883',
    projectId: 'bank-bocil-ec07c',
    storageBucket: 'bank-bocil-ec07c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVjU-B0Lc_nrzAF-hZHfxLAt8ICrWICWg',
    appId: '1:1026154962883:ios:faa1e074f426b34030e776',
    messagingSenderId: '1026154962883',
    projectId: 'bank-bocil-ec07c',
    storageBucket: 'bank-bocil-ec07c.firebasestorage.app',
    iosBundleId: 'com.example.bankbocil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVjU-B0Lc_nrzAF-hZHfxLAt8ICrWICWg',
    appId: '1:1026154962883:ios:faa1e074f426b34030e776',
    messagingSenderId: '1026154962883',
    projectId: 'bank-bocil-ec07c',
    storageBucket: 'bank-bocil-ec07c.firebasestorage.app',
    iosBundleId: 'com.example.bankbocil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfSgs-3R5rNSZctxWoQvy9nTaAa_gyXCs',
    appId: '1:1026154962883:web:e5f1debce6e7fddc30e776',
    messagingSenderId: '1026154962883',
    projectId: 'bank-bocil-ec07c',
    authDomain: 'bank-bocil-ec07c.firebaseapp.com',
    storageBucket: 'bank-bocil-ec07c.firebasestorage.app',
    measurementId: 'G-K7J6LX7640',
  );
}
